### ISSUE TITLE
NPE from OneDrive.getAccessTokenFromRefreshToken

### ISSUE THREAD

**Issue by hakanai** [nicknux/onedrive4j#2]
We get an NPE calling `getAccessTokenFromRefreshToken`:

    java.lang.NullPointerException
    	at com.nickdsantos.onedrive4j.OneDrive.getAccessTokenFromRefreshToken(OneDrive.java:174)
    	at OurCode.getAccessTokenFromRefreshToken(OneDriveAuthenticator.java:77)

Trying to debug further, it seems that an error occurred. I think the library should be checking for this and throwing a better exception.

```
rawToken = {java.util.LinkedHashMap@5116}  size = 2
 0 = {java.util.LinkedHashMap$Entry@5126} "error" -> "invalid_grant"
 1 = {java.util.LinkedHashMap$Entry@5127} "error_description" -> "The user could not be authenticated or the grant is expired. The user must first sign in and if needed grant the client application access to the requested scope."
```

**Comment by nicknux** [comment]
@trejkaz Good catch. Do a PR and I'll review it.
